# Generated by `mise run release:formula` from the checksums.txt this release
# published and cosign signed. Do not edit by hand: tools/release/tap.sh derives
# this file again from the release and exits 2 while the tap differs.
#
# It installs the published bytes and never rebuilds them, so the SHA-256 brew
# checks is the one the release signed — the same reasoning the container image
# follows.
class Feint < Formula
  desc "Local emulator of the Scaleway, Outscale and Exoscale clouds"
  homepage "https://github.com/stephrobert/feint"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/stephrobert/feint/releases/download/v0.9.0/feint-darwin-amd64"
      sha256 "c1ac05141df079d142a43b9f8d212a84e9c52661af98cb92753860c05aeaace8"
    end

    on_arm do
      url "https://github.com/stephrobert/feint/releases/download/v0.9.0/feint-darwin-arm64"
      sha256 "af8446dfaff8b657637bfbf295fe8ea58bcecb7fe3ab4fea33fa2d3790ed053b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stephrobert/feint/releases/download/v0.9.0/feint-linux-amd64"
      sha256 "fa7b9c099239a5e66fadba7312722f84e5ba34ff606540101516a7170965e28a"
    end

    on_arm do
      url "https://github.com/stephrobert/feint/releases/download/v0.9.0/feint-linux-arm64"
      sha256 "de1d7c093b7755afbfbf053cb5dadf832f3b713d67c00316c39d2023732c34cd"
    end
  end

  def install
    published = Dir["feint-*"]
    odie "expected one published feint binary in the download, found #{published.length}" if published.length != 1
    bin.install published.first => "feint"
  end

  test do
    assert_match "v#{version}", shell_output("#{bin}/feint version")
  end
end
