# Generated by `mise run release:formula` from the checksums.txt this release
# published and cosign signed. Do not edit by hand: tools/release/tap.sh derives
# this file again from the release and exits 2 while the tap differs.
#
# It installs the published bytes and never rebuilds them, so the SHA-256 brew
# checks is the one the release signed — the same reasoning the container image
# follows.
class Feint < Formula
  desc "Local emulator of the Scaleway, Outscale and Exoscale clouds"
  homepage "https://github.com/stephrobert/feint"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/stephrobert/feint/releases/download/v0.10.0/feint-darwin-amd64"
      sha256 "1ff83266163a04ac54cd0304e8f932aecbb052050ba544c176d3c29b5f7de597"
    end

    on_arm do
      url "https://github.com/stephrobert/feint/releases/download/v0.10.0/feint-darwin-arm64"
      sha256 "094728ab95e8123919ef9cf500246e2cdf2ffa0528930596e932a5321a998397"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stephrobert/feint/releases/download/v0.10.0/feint-linux-amd64"
      sha256 "c9f17966451c68de4110a4d09b4b3d1f14f34f305b094984f6d5be4ec60002a7"
    end

    on_arm do
      url "https://github.com/stephrobert/feint/releases/download/v0.10.0/feint-linux-arm64"
      sha256 "c54ba8e4700c330b7e4fd1c0ca000d0acd85f0c925cb43456a4da61a3fdcec13"
    end
  end

  def install
    published = Dir["feint-*"]
    odie "expected one published feint binary in the download, found #{published.length}" if published.length != 1
    bin.install published.first => "feint"
  end

  test do
    assert_match "v#{version}", shell_output("#{bin}/feint version")
  end
end
